### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by unfokus** [cccc/autoc4_shiny#1]
Hello!
How is the code licensed? I would like to use some parts of the code for the Control Panel of the Maschinendeck (Hackerspace in Trier)

**Comment by Florob** [comment]
Hi.
MQTT WS, jQuery, and Bootstrap are under their own license as noted in the respective files.
Everything else is technically unlicensed right now. Absolutely do feel free to reuse it though.
I'll try to add proper licensing information to the project in the next days, most likely an MIT license.

**Comment by unfokus** [comment]
Super! Thank you!
